<?xml version="1.0"?>

<robot name="mobile_manipulator" xmlns:xacro="http://ros.org/wiki/xacro">

  <!-- argument -->
  <xacro:arg name="robot_namespace" default="/"/>
  <xacro:arg name="kinect1_enabled" default="true"/>
  <xacro:arg name="kinect2_enabled" default="false"/>
  <xacro:arg name="realsense_enabled" default="true"/>
  <xacro:arg name="ur_enabled" default="true"/>
  <xacro:arg name="gripper_enabled" default="true"/>

  <!-- inspector_bot -->
  <xacro:include filename="$(find mm_description)/urdf/components/inspector_bot.urdf.xacro" />  
  <xacro:include filename="$(find mm_description)/urdf/accessories/kinect_tilted_camera.urdf.xacro"/>
  <xacro:include filename="$(find ur_description)/urdf/ur5.urdf.xacro" />
  <xacro:include filename="$(find robotiq_2f_85_gripper_visualization)/urdf/robotiq_arg2f_85_model_macro.xacro" />
  <xacro:include filename="$(find realsense2_description)/urdf/_d435.urdf.xacro" />

  <!-- ur5 robot -->
  <xacro:if value="$(arg ur_enabled)">    
    <xacro:property name="ur5_z_location" value="${base_center_height + base_z_size/2}" />
    <xacro:property name="ur5_x_location" value="0.175" />
    
    <joint name="ur_fixed_joint" type="fixed">
      <parent link="bare_base_link" />
      <child link="base_link" />
      <origin xyz="${ur5_x_location} 0.0 ${ur5_z_location}" rpy="0.0 0.0 -${M_PI/2}" />
    </joint>

    <xacro:ur5_robot prefix="" joint_limited="false"/>

    <!-- gripper -->
    <xacro:if value="$(arg gripper_enabled)">  
      
      <joint name="ur_gripper_fixed_joint" type="fixed">
        <parent link="tool0"/>
        <child link="robotiq_arg2f_base_link"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
      </joint>

      <joint name="ur_ee_fixed_joint" type="fixed">
        <parent link="tool0"/>
        <child link="robotiq_ee"/>
        <origin xyz="0 0 0.125" rpy="0 0 0"/>
      </joint>

      <link name="robotiq_ee"/>
      <xacro:robotiq_arg2f_85 prefix=""/>
    </xacro:if>
  </xacro:if>

  <!-- kinect -->  
  <xacro:if value="$(arg kinect1_enabled)">
    <xacro:arg name="kinect1_base_xyz" default="${base_x_size/2 + 0.041} 0 ${base_center_height + base_z_size/2 - 0.071}"/>
    <xacro:arg name="kinect1_base_rpy" default="0 0 0"/>
    <xacro:arg name="kinect1_tilt_angle" default="0"/>
  
    <xacro:kinect_tilted_camera prefix="kinect1" robot_namespace="$(arg robot_namespace)" 
      base_xyz="$(arg kinect1_base_xyz)" base_rpy="$(arg kinect1_base_rpy)" tilt_angle="$(arg kinect1_tilt_angle)"/>
  </xacro:if>

  <xacro:if value="$(arg kinect2_enabled)">
    <xacro:property name="kinect2_height" value="0.40"/>
    <xacro:arg name="kinect2_base_xyz" default="${-base_x_size/2 - profile_size/2 + 0.03} ${-base_y_size/2 + profile_size*1.5} ${base_center_height + base_z_size/2 + kinect2_height}"/>
    <!-- <xacro:arg name="kinect2_base_rpy" default="0 0 -0.785"/> -->
    <xacro:arg name="kinect2_base_rpy" default="0 0 -0.795"/>
    <!-- <xacro:arg name="kinect2_tilt_angle" default="-0.471"/> -->
    <xacro:arg name="kinect2_tilt_angle" default="-0.42"/>

    <xacro:kinect_tilted_camera prefix="kinect2" robot_namespace="$(arg robot_namespace)" 
      base_xyz="$(arg kinect2_base_xyz)" base_rpy="$(arg kinect2_base_rpy)" tilt_angle="$(arg kinect2_tilt_angle)"/>
  </xacro:if>

  <xacro:if value="$(arg realsense_enabled)">
    <xacro:property name="realsense_height" value="${0.415+0.077}"/>
    
    <link name="realsense_mount_link" />
    
    <joint name="base_realsense_fixed_joint" type="fixed">
      <parent link="bare_base_link"/>
      <child link="realsense_mount_link"/>
      <origin xyz="${-base_x_size/2 - profile_size/2} ${-base_y_size/2 + profile_size*1.5} ${base_center_height + base_z_size/2 + realsense_height}" rpy="0 0 ${-M_PI/4}"/>
    </joint>

    <link name="realsense_base_link" />
    <joint name="realsense_mount_fixed_joint" type="fixed">
      <parent link="realsense_mount_link"/>
      <child link="realsense_base_link"/>
      <origin xyz="0.035 0 0.025" rpy="0 ${M_PI/6} 0"/>
    </joint>

    <xacro:sensor_d435 parent="realsense_base_link">
      <origin xyz="0.010 0 -0.0125" rpy="0 0 0"/>
    </xacro:sensor_d435>

  </xacro:if>

</robot>
