<?xml version="1.0"?>

<robot name="mobile_manipulator" xmlns:xacro="http://ros.org/wiki/xacro">

  <!-- argument -->
  <xacro:arg name="robot_namespace" default="/"/>
  <xacro:arg name="kinect1_enabled" default="true"/>
  <xacro:arg name="kinect2_enabled" default="true"/>
  <xacro:arg name="ur_enabled" default="false"/>
  <xacro:arg name="gripper_enabled" default="false"/>

  <!-- inspector_bot -->
  <xacro:include filename="$(find mm_description)/urdf/components/inspector_bot.urdf.xacro" />  
  <xacro:include filename="$(find mm_description)/urdf/accessories/kinect_tilted_camera.urdf.xacro"/>

  <!-- kinect -->  
  <xacro:if value="$(arg kinect1_enabled)">
    <xacro:arg name="kinect1_base_xyz" default="${base_x_size/2 + 0.041} 0 ${base_center_height + base_z_size/2 - 0.071}"/>
    <xacro:arg name="kinect1_base_rpy" default="0 0 0"/>
    <xacro:arg name="kinect1_tilt_angle" default="0"/>
  
    <xacro:kinect_tilted_camera prefix="kinect1" robot_namespace="$(arg robot_namespace)" 
      base_xyz="$(arg kinect1_base_xyz)" base_rpy="$(arg kinect1_base_rpy)" tilt_angle="$(arg kinect1_tilt_angle)"/>
  </xacro:if>

  <xacro:if value="$(arg kinect2_enabled)">
    <xacro:property name="kinect2_height" value="0.40"/>
    <xacro:arg name="kinect2_base_xyz" default="${-base_x_size/2 - profile_size/2 + 0.03} ${-base_y_size/2 + profile_size*1.5} ${base_center_height + base_z_size/2 + kinect2_height}"/>
    <!-- <xacro:arg name="kinect2_base_rpy" default="0 0 -0.785"/> -->
    <xacro:arg name="kinect2_base_rpy" default="0 0 -0.795"/>
    <!-- <xacro:arg name="kinect2_tilt_angle" default="-0.471"/> -->
    <xacro:arg name="kinect2_tilt_angle" default="-0.42"/>

    <xacro:kinect_tilted_camera prefix="kinect2" robot_namespace="$(arg robot_namespace)" 
      base_xyz="$(arg kinect2_base_xyz)" base_rpy="$(arg kinect2_base_rpy)" tilt_angle="$(arg kinect2_tilt_angle)"/>
  </xacro:if>

</robot>
