scan_filter_chain:
- name: box
  type: laser_filters/LaserScanBoxFilter
  params:
    box_frame: /base_laser_link
    min_x: -1.0
    max_x: 0.2
    min_y: -0.9
    max_y: 0.9
    min_z: -1.0
    max_z: 1.0